### ISSUE TITLE
fix(dashboard): type error in PermissionBadge size prop

### ISSUE THREAD

**Issue by fdemusso** [fdemusso/BeechCMS#422]
Discovered while fixing #387: `apps/dashboard/src/features/rbac/components/permission-badge.tsx:47` passes `size` to a component whose props type doesn't declare it, failing `pnpm type-check` on `@beechcms/dashboard`.

```
error TS2769: No overload matches this call.
Property 'size' does not exist on type 'IntrinsicAttributes & { className?: string | undefined; }'.
```

Predates #387 (introduced in fcff098).

**Comment by fdemusso** [comment]
Resolved in commit 9d1a5dd pushed to devs branch.
